runtime: php83
basic_scaling:
  max_instances: 1
runtime_config:
  enable_stackdriver_integration: true
entrypoint: serve public/index.php
handlers:
  - url: /assets
    static_dir: public/assets
  - url: .*
    script: auto
